# Generated by Django 5.2.13 on 2026-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['new', 'learning', 'review', 'lapsed'])), name='card_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 0)), name='card_interval_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('repetitions__gte', 0)), name='card_repetitions_non_negative'),
        ),
    ]
