# Generated by Django 5.2.13 on 2026-04-26 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_card_card_state_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', 'updated_at', 'id'], name='card_sync_cursor_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'updated_at', 'id'], name='deck_sync_cursor_idx'),
        ),
    ]
