# Generated by Django 5.2.13 on 2026-04-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_card_deleted_at_deck_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='card_sync_cursor_idx',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE decks_card AS card
               SET user_id = deck.user_id
              FROM decks_deck AS deck
             WHERE card.deck_id = deck.id
               AND card.user_id IS NULL
            """,
            reverse_sql="UPDATE decks_card SET user_id = NULL",
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'updated_at', 'id'], name='card_sync_cursor_idx'),
        ),
    ]
