# Generated by Django 5.2.13 on 2026-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_add_card_user_sync_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_client_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='last_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='last_client_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='last_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
