# Generated by Django 5.2.13 on 2026-04-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_card_card_state_valid_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', ['again', 'hard', 'good', 'easy'])), name='review_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('duration_ms__gte', 0)), name='review_duration_ms_non_negative'),
        ),
    ]
