# Generated by Django 5.2.13 on 2026-04-25 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.UUIDField()),
                ('op', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('review', 'Review')], max_length=16)),
                ('payload', models.JSONField()),
                ('client_ts', models.DateTimeField()),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('conflict', 'Conflict')], default='pending', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'device_id', 'server_ts'], name='syncevent_user_device_idx'), models.Index(fields=['user', 'status', 'server_ts'], name='syncevent_user_status_idx')],
            },
        ),
    ]
