# Generated by Django 5.2.13 on 2026-04-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.CheckConstraint(condition=models.Q(('op__in', ['create', 'update', 'review'])), name='syncevent_op_valid'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'applied', 'conflict'])), name='syncevent_status_valid'),
        ),
    ]
