# Generated by Django 5.2.13 on 2026-04-27 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_syncevent_syncevent_op_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncevent',
            name='syncevent_op_valid',
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='op',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('review', 'Review')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.CheckConstraint(condition=models.Q(('op__in', ['create', 'update', 'delete', 'review'])), name='syncevent_op_valid'),
        ),
    ]
